---
fixtures:
  repositories:
    augeas_core: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld.git
    haveged: https://github.com/simp/pupmod-simp-haveged.git
    iptables: https://github.com/simp/pupmod-simp-iptables.git
    pki: https://github.com/simp/pupmod-simp-pki.git
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
  symlinks:
    libreswan: "#{source_dir}"
